### ISSUE TITLE
Make baseUrl an option of constructor

### ISSUE THREAD

**Issue by aloysius-pgast** [zoeyg/binance#44]
Hi.

Do you think it could be possible to make baseUrl an option ? After Binance outage, I noticed that https://us.binance.com was working for me while https://www.binance.com was not so it would have been nice to be able to pass the new url in the constructor.

Thanks for your work, I'm using your lib for my multi-exchange project (https://mpe-demo.crazyme.net/ui/#/exchanges/binance/prices/USDT-NEO)

**Comment by zcauchon** [comment]
Until this PR is implemented you can update the URL after you create the client:
<code>
this.binanceAuthClient = new this.binanceAPI.BinanceRest({	key: xyz, secret: xyz});
this.binanceAuthClient._baseUrl = 'https://us.binance.com';
</code>

**Comment by tiagosiebler** [comment]
Resolved via #46
