### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by SMUsamaShah** [zoeyg/binance#45]
I thought it was plain JavaScript which I can simply link and use. 

1. Installed Node
2. `cd binance-master`
3. `npm install`

I have never used node but I am good with JavaScript. Can you list down in few steps that how to use/run this?

**Comment by nieroda** [comment]
in your directory "npm install --save binance"

**Comment by apexearth** [comment]
It looks like maybe you've checked out the repository. 
You typically should only need to do that if you're looking to make changes to the repository.
If you just want to use this in another project, do the following:

You may first want to have the package.json file: `npm init`
Then install the binance project: `npm install binance --save`
Then use it in your code via `const binance = require('binance')`

**Comment by SMUsamaShah** [comment]
Thanks, I was trying to use it from this repository. Installing from package repository using `npm install binance --save` worked.
