### ISSUE TITLE
Ticker return multiple symbol?

### ISSUE THREAD

**Issue by ewwink** [zoeyg/binance#48]
for single symbol
```
https://api.binance.com/api/v1/ticker/price?symbol=LTCBTC
{
  "symbol": "LTCBTC",
  "price": "4.00000200"
}
```

how to get the result 2 or more symbols?
```
[
  {
    "symbol": "LTCBTC",
    "price": "4.00000200"
  },
  {
    "symbol": "ETHBTC",
    "price": "0.07946600"
  }
]
```

**Comment by apexearth** [comment]
I believe you can either get one:
 `https://api.binance.com/api/v1/ticker/price?symbol=LTCBTC`
 or all:
 `https://api.binance.com/api/v1/ticker/price`

There is no method for supplying multiple symbols in your request.

**Comment by Garglesoap** [comment]
That's odd because double symbol calls are given in the API documentation.

**Comment by apexearth** [comment]
> That's odd because double symbol calls are given in the API documentation.

Can you link to that part of the documentation?

**Comment by Garglesoap** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#symbol-order-book-ticker

It gets LTCBTC and ETHBTC

**Comment by apexearth** [comment]
> Best price/qty on the order book for a symbol or symbols.

> If the symbol is not sent, bookTickers for all symbols will be returned in an array.

Given that the parameter `symbol` is singular, and also has a back-end regex filter of `^[A-Z0-9_]{1,20}$`, I don't believe you can use it to get more than one symbol at a time.

When you omit that parameter, you'll end up getting all symbols.
I believe the example data they show is limited to two symbols just for the sake of brevity.

**Comment by karatedog** [comment]
This is the new link: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#symbol-order-book-ticker
