### ISSUE TITLE
Question: cancelling partially filled orders

### ISSUE THREAD

**Issue by matteoantoci** [zoeyg/binance#56]
I don't know if this is the right place to ask, in case it's not just close the ticket.

What I'm trying to understand is what happens when I cancel a partially filled order. 
Let me explain: I know that a part of the order is bought and another part is cancelled but I'm wondering if the order status will still be `PARTIALLY_FILLED` or it becomes `CANCELED` and how to handle that case.

Thanks!

**Comment by laurynas-karvelis** [comment]
If your order got `PARTIALLY_FILLED` in the midst of you trying to cancel it. Only the unbought/unsold quantity will be actually cancelled. The remaining is purchased/sold by the exchange and you have to deal with that remainder yourself. Which is you have to limit/market sell/buy the quantity that got `PARTIALLY_FILLED`.

**Comment by aloysius-pgast** [comment]
Based on my experience, status will be _FILLED_. _CANCELED_ happens only when cancelling an order before any quantity was purchased/sold. And _PARTIALLY_FILLED_ is only possible for an order which is still opened. Again, this is based on my own experience

**Comment by matteoantoci** [comment]
I had a look at the Binance's order history to be sure. It all comes down to fulfilled quantity, so when you cancel an order:
- if the quantity to fulfil is entirely covered you will have  a `FILLED` status
- if the quantity to fulfil is partially covered you will have  a `PARTIALLY_FILLED` status
- if the quantity to fulfil is not covered at all you will have a `CANCELED` status

The confusion comes from the `cancelOrder` action that is homonymous to the `CANCELED` status. Thank you to all for the contributions!

**Comment by tiagosiebler** [comment]
Closing as stale/answered. If more action is required, feel free to reopen.

**Comment by immartian** [comment]
> * if the quantity to fulfil is entirely covered you will have  a `FILLED` status
> * if the quantity to fulfil is partially covered you will have  a `PARTIALLY_FILLED` status
> * if the quantity to fulfil is not covered at all you will have a `CANCELED` status


Cleary I got diffferent result:
```
{'symbol': 'CRVUSDT', 'origClientOrderId': 'Mqw5onfrrtJu4RI2pWM3HP', 'orderId': 11268364, 'orderListId': -1, 'clientOrderId': 'hLp5XljG7euapITWQbwC6C', 'price': '5.30000000', 'origQty': '11.58700000', 'executedQty': '11.23900000', 'cummulativeQuoteQty': '59.56670000', 'status': 'CANCELED', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'SELL'}
```
The order above was canceled in the middle of the execution. I received "CANCELLED" but actually it's partially fulfilled. It caused me a big headache to reconcile this.  Any ideas?

**Comment by tato69** [comment]
@immartian might be a bit late to answer you but...
when the status is canceled you need to check 'executedQty' 
If is 0 then you order had no fills before cancellation
if is more than 0 you order was partially filled before cancellation

**Comment by immartian** [comment]
> when the status is canceled you need to check 'executedQty'

Yes, it's solved by checking this key. Thanks anyway.
