### ISSUE TITLE
Rewriting in functional style

### ISSUE THREAD

**Issue by dmitriz** [zoeyg/binance#57]
I wonder about the interest to simplify this library with functional style.

Here is essentially complete implementation for the websocket part, without beautifier
(which would be a composition with another transformer):

```js
const { map, curry, pipe, compose } = require('ramda')
const BASE_URL = 'wss://stream.binance.com:9443/ws/'

// the url getter is independent of the rest of the code
const getUrl = (type, symbol) => [
  BASE_URL, 
  symbol.toLowerCase(),
  `@`,
  type
].join('')

// general purpose websocket factory
const WebSocket = require('ws')
const createWS = path => cb => 
  new WebSocket(path).on('message', cb)

// Functor structure on the CPS (continuation-passing-style) functions
const cpsMap = f => cpsFn => 
  // new CPS function
  cb => cpsFn(compose(cb, f))

// Final WS stream from Binance as functional composition
const getStream = pipe
(
  getUrl
, createWS // returns f: cb -> void
// apply map from the CPS functor
, cpsMap(JSON.parse)
)

// start WS stream and pass the callback
getStream('trade', 'BNBBTC')(console.log)
```

**Comment by slidenerd** [comment]
I dont mind the functional style but please refrain from using foreach loop, native or lodash or otherwise, they are a joke in performance and normally I wouldnt care about them if we were building a student database website but in an API like this where 2 orders literally arrive at the same millisecond, 86% slower loops are a no no

**Comment by davalapar** [comment]
nested function calls are expensive too. very expensive.

**Comment by tiagosiebler** [comment]
Imo a rewrite of this existing and otherwise fully functioning lib is overkill - it's likely to introduce bugs rather than fix existing issues or limitations. Refactoring has benefits, but I don't think a rewrite of this kind is a benefit right now. @zoeyg
