### ISSUE TITLE
Can we get the historical data? (v1/ticker/allPrices)

### ISSUE THREAD

**Issue by askucher** [zoeyg/binance#67]
This is how we get current prices
```
https://api.binance.com/api/v1/ticker/allPrices
```

Can we get the historical prices? 
```
https://api.binance.com/api/v1/ticker/allPrices?date=20170303 
```

**Comment by tiagosiebler** [comment]
This is dictated by Binance's API designs. All this module does is provide a wrapper around how Binance's API's are designed. You could use klines to get historic prices.
