### ISSUE TITLE
How to get only BTC pair prices?

### ISSUE THREAD

**Issue by anjilite7** [zoeyg/binance#68]
I try to use https://api.binance.com/api/v3/ticker/price but it retrieve all tickers at once, i need just BTC pair prices.

**Comment by tiagosiebler** [comment]
Store the results in an array then filter elements by your condition - pseudo example:
```javascript
const allTickers = ...logic to get all tickers from API shown above;
const btcPairs = allTickers.filter(ticker => ticker.symbol.endsWith('BTC'));
```

**Comment by tiagosiebler** [comment]
Closing as stale/answered. If needed, feel free to reopen.
