### ISSUE TITLE
maker vs isBuyerMaker

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [zoeyg/binance#69]
There is already a question about this here... But I still couldn't get my head around it.

My observation:

maker: true // The trade should be marked RED ?
maker: false // The trade should be marked GREEN ? 
isBuyerMaker: true  //  I don't know what this is or what it's used for ? 

I just found contradictory information about it, please someone clarify.

I mean what should it mean "IS BUYER MAKER" ? What I buy my own order ?
I buy what I made? What kind of vocabulary is this?

**Comment by yosietserga** [comment]
Here you can expand the semantics https://cryptocurrencyfacts.com/maker-vs-taker-cryptocurrency/
