### ISSUE TITLE
Making /api/v3/myTrades work without passing a specific symbol 

### ISSUE THREAD

**Issue by bralca** [zoeyg/binance#71]
I would like to retrieve all my past trades, but I don't remember all the symbols I have traded with. Right now it's not possible to get all my trades without passing a symbol, so to do that I have to get all the available symbols in Binance and then loop through and make a request to myTrades for each symbol. Besides making too many requests, many of them return of course an empty response.  

Do you plan to fix this anytime soon? 

Thanks

**Comment by apexearth** [comment]
You'll have to bring that up with binance. I believe this package has no direct affiliation with binance and thus no control of how it designs it's API.

**Comment by tiagosiebler** [comment]
Closing, in agreement with @apexearth's statement
