### ISSUE TITLE
Remove or fix faulty index.d.ts file

### ISSUE THREAD

**Issue by jakesee** [zoeyg/binance#72]
I think you have a faulty or outdated index.d.ts file that is causing compiling issues for typescript users.

To fix the problem, easiest way is to remove the index.d.ts from the master branch and update npm repository. The typescript user can create their own index.d.ts file with this line to fix their problem.

> declare module "binance";

Nevertheless thanks for this awesome API package!

**Comment by zoeyg** [comment]
This may have originally been added for intellisense/autocompletion I believe.  Things have likely changed since and it may no longer be needed.  I'll investigate.

**Comment by rubengmurray** [comment]
Hi @zoeyg 

My comment isn't strictly related to this issue but It would be great to see some TypeScript support added back in. 

I think it would be a good idea to get an `index.d.ts` file available on DefinitelyTyped (`@types/binance`) to install separately, the version of which can match the version of this project that it was made for.

Adding it into this repository has some drawbacks with versioning highlighted by @jakesee given the repository itself is written in JavaScript.

I've made a start on this here: https://github.com/rubengmurray/types-binance/blob/master/index.d.ts. It's not complete, but it does deliver for me already.

If there's anyone that would be willing to help to get this in-sync with everything in the current version that would be brilliant.
